### ISSUE TITLE
Apache Commons Http Libs

### ISSUE THREAD

**Issue by seandelaney** [maxhille/panda-lib#1]
Where did you get the Apache Commons Http Libs?  I can't find it.

**Comment by maxhille** [comment]
Looks like it went here some time ago: http://hc.apache.org/

**Comment by seandelaney** [comment]
Hi

Is it possible to get a copy of all the dependencies as I'm having trouble finding them all.  I've got a few but then these are requiring more libraries which I can't find.  I want to use your library for a Panda stream project.

**Comment by seandelaney** [comment]
I'm getting a step closer.  No compile errors since I managed to get JAR files. However I do get this error when I attempt to create a new Panda object:

Exception in thread "pool-7-thread-1" java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
    at com.lambdasoup.panda.Panda.<clinit>(Panda.java:46)
    at com.miituu.wms.module.Miituu$WriteListener.onWriteComplete(Miituu.java:25)
    at com.wowza.wms.application.ApplicationInstance.notifyMediaWriterOnWriteComplete(Unknown Source)
    at com.wowza.wms.mediawriter.flv.MediaWriterFLV.writePackets(Unknown Source)
    at com.wowza.wms.stream.record.MediaStreamRecordWriter.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 8 more

In my class I'm calling the Panda library like this:

Panda panda = new Panda(accessKey, cloudId, secretKey, apiHost);

**Comment by maxhille** [comment]
looks like the gson dependency is not fulfilled. please check the pom.xml for the library versions.
